### PR TITLE
add utf8 encoding to xml

### PR DESCRIPTION
**Pull request by MJKruszewski**

### CODE REVIEW

**Comment by dashnine** [comment]
Closing due to conflict. I don't see those lines in the larger PR -- did you determine them to be unnecessary?  I almost went to just add them in, but figure if you want credit for the change you might just prefer to update the PR and resubmit :)

**Comment by MJKruszewski** [comment]
Hello @dashnine, long time no see :D, if you can edit by hand, cred not needed, just utf8 export :D. Now I start focusing on introducing new DLC changes.

**Comment by dashnine** [comment]
> Hello @dashnine, long time no see :D, if you can edit by hand, cred not needed, just utf8 export :D. Now I start focusing on introducing new DLC changes. (so we can close this pr)

Howdy @MJKruszewski !  Sorry for the delayed response -- I'll take a look :)

**Comment by dashnine** [comment]
Closing -- #243 implemented this!  Thanks again, and sorry for the delay, @MJKruszewski !

**Pull request closed without merging**
