### PR TITLE
#215 Add content related to FoV

### PR DESCRIPTION
**Pull request by MJKruszewski**

### CODE REVIEW

**Comment by dashnine** [comment]
Holy moley, this is excellent.  Apologies in advance -- it may take me a couple days to get this reviewed and merged.  Very exciting--thanks!  Did you run into any problems or oddities I should look out for in particular?

**Comment by dashnine** [comment]
Ok, I lied and started reviewing this evening. A few things cropped up:

Isawa Tensai
	1) Requires choosing 2 of any one ring.  I don't think there's code for this right now, so will either need a special case, or a note in the class description noting the requirement.  The latter is....much easier

	2) Inspired Invocations
		a) The first technique selection should be choosing from all rank one (inspired) invocations--looks like there's just one option from each element.  As a stand in, we could ignore that for now and just say All Rank 1 Invocations'. That said, that leads me to...
		b) All of this school's curriculum selections are only from inspired elements.  What we may need to do is add an optional field and selection box for it (similar to how we handled kitsune impersonator), especially since it'll come up with leveling up and XP costs into curriculum.  The more I think about it, the more I think this is unavoidable...

	3) Samurai heritages will need some tweaking -- right now, it looks like two categories of things will be needed:
		a) Adding in special advantages along the lines of things like 'Support of Seppun' to match the selections, so that they get added properly, and 
		b) Tweaking the verbiage and triggers so that it gives secondary selections on the FoV heritages.  For instance, we'll need to pair up something to 'weapon' :)  Samurai heritages are *always* the biggest pain in the process.

Altogether, though, this is *epic*.  I'm going to create an FoV branch and merge it into that for further work before we push into master, and add some issues to the board to cover these gaps, but I can't thank you enough!  If you opt to work on any of these, that's awesome (and let me know, so I don't double-your-work!), but I'm happy to use your efforts to jump-start some changes regardless. :)

**Comment by dashnine** [comment]
Will be doing work on dashnine:FoV_PR until it's ready to roll into master!

**Comment by MJKruszewski** [comment]
@dashnine Thanks, actually problems which I meet was mostly with Isawa - as you mentioned mechanics with this school are pretty tricky, after entering all data to json's I was exhausted to implement this in code, also not pretty familiar with QT (but now I have prepared dev env for future), but to the point, thins needed rethinking/checking:

1. Create special case for Isawa selected ring
2. Depending on Isawa selected ring, select proper "Inspired Element Invocations" - for now this is just a Invocations, so any group will be accepted, need to be done same way as Fire Shuji, etc.
3. Incite True Nature - I do not find anywhere in my books a definition of this technique, needed real source, for now put this as FoV
4. Matsu Beastmaster - there is probably thing also to rethink, I created Two Bonded Animals personal effect to make it as choice related to starting outfit (FoV page 80)
```
...1-2 bonded animals...
``` 
5. Imbue Outburst - Daidoji Harrier School, here also i didn't found a source in FoV, needed a correct one
6. Blessed Treasures (FoV page 92), i have no idea how to approach to this (maybe as a Personal Effects)

I want to thank for your review! As You have seen, I also have done some 'cleaning' in schema to match actually enum values. 

About changes related to codebase, if I will be having some spare time, probably I will start implementation of this special case for Isawa. 

Also, can you tell me which DLC also is missing, in near future if I will be having free time I can also enter data

**Comment by MJKruszewski** [comment]
Ah my bad, I forgot about skill selection in Isawa School 

7. Depending on selected main ring - all invocations from that ring, rank 1 must be available to select (ofc. we can do this with manual input, but on new DLC's release there will be a problem)

**Comment by dashnine** [comment]
For what it's worth -- I believe there's already support for, say, Rank 1 Fire Invocations (the technique filters check for secondary types). I suspect that rather than adding a 'Inspired Element' field, it'll be easier to make four copies of the school: Isawa Tensai (Earth), Isawa Tensai (Fire), etc.  Then we can just specify the element in the curriculum and Starting invocations....which should be both easier and less error prone!

**Pull request merged**
