### PR TITLE
Fixed unused variable warnings

### PR DESCRIPTION
**Pull request by OpenNingia**
I've fixed some warnings related to unused parameters

### CODE REVIEW

**Comment by dashnine** [comment]
Awesome--thanks!  I'll double-check it over lunch or after work--looks great at a glance!

**Comment by dashnine** [comment]
Looks good to me--thanks again!  I think there are a few others that could use this treatment, for that matter.

(Unrelated -- huge fan, by the way! L5RCM was and is amazing! I did a double-take when I saw this pull request.)

**Comment by OpenNingia** [comment]
Thanks, sadly L5RCM was a big time sink I can no longer afford. However I'm glad that there are others passionate about this great game :)

**Comment by dashnine** [comment]
Well, without your prior work, I'd have never managed to get my first L5R game together in the first place! =) Thanks for taking the time then and now--and your contributions are always welcome!

**Pull request merged**
